version: "3.7"

services:
  spring-boot:
    build:
      context: ./
      dockerfile: Dockerfile
    image: trashgo_backend
    ports:
      - "8888:8888"
    container_name: trashgo_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://121.124.124.8:3306/stac?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: stac
      SPRING_DATASOURCE_PASSWORD: stac2022!@
    networks:
      - backend-network

networks:
  backend-network:
