spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource: # DB ?? ??
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.124.124.8:3306/stac?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: stac
    password: stac2022!@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8888
